name: inventory-env
channels:
  - conda-forge
dependencies:
  - python=3.13
  - numpy
  - xarray
  - fsspec
  - cfgrib
  - eccodes
  - zarr
  - gcsfs
  - s3fs
  - netcdf4
  - h5netcdf
  - requests
  - aiohttp
